config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "workouts#index"
  resources :workouts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update]
  
  def index
    @workouts = current_user.workouts 
  end
  
  def show
  end
  
  def new
    @workout = Workout.new
  end
  
  def create 
    @workout = current_user.workouts.new(workout_params)
      if @workout.save
        flash[:success] = "Workout Created"
        redirect_to workouts_path
      else
        flash[:error] = "Error #{@workout.errors.full_messages.join("\n")}"
        render :new
      end
  end
  
  def edit
  end
  
  def update
    if @workout.update(workout_params)
      redirect_to workouts_path
    else
      render :edit
    end
  end
  
  def destroy
    @workout.destroy
    redirect_to workouts_path
  end
  
  private
    def workout_params
      params.require(:workout).permit(:name, :time)
    end
  
    # don't just find by the workout model or you may potentially be able to view other users workouts
    def set_workout
      @workout = current_user.workouts.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="#e53935 red darken-1">
    <div class="nav-wrapper">
    <%= link_to "Exercise", workouts_path, class: "brand-logo" %>
      <a href="#" class="brand-logo">Exercise Time</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user %>
       <li>
      <%= link_to "Workouts", workouts_path %>
        </li>
      
      <li>
      <%= link_to "Log out", destroy_user_session_path, method_delete: :delete %>
        </li>
       <% else %>
       <li>
       <%= link_to "Login", user_session_path %>
       </li>
       <li>
       <%= link_to "Register", new_user_registration_path %>
       </li>

       <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "/layouts/navbar" %>
  <div class= "container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
 <%= yield %>
  </body>
</html>

app/views/workouts/edit.html.erb
<h1>Workouts#edit</h1>
<p>Find me in app/views/workouts/edit.html.erb</p>

app/views/workouts/index.html.erb
<h2>Welcome <%= current_user.first_name %></h2>
<hr />
<%= link_to "Add Workout", new_workout_path %>
<h5>Your Workouts</h5>
<ul>
  <% @workouts.each do |workout| %>
    <li>
      <%= workout.name %> - Time In Seconds <%= workout.time %> 
    </li>
  <% end %>
</ul>

app/views/workouts/new.html.erb
<h1>Add A Workout</h1>
<%= form_with(model: @workout, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.label :"Time In Seconds" %>
    <%= f.number_field :time %>
  </div>
  <%= f.submit %>
<% end %>

app/views/workouts/show.html.erb
<h1>Workouts#show</h1>
<p>Find me in app/views/workouts/show.html.erb</p>